apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}
rules:
- apiGroups:
    - ""
  resources:
    - "pods"
    - "services"
    - "nodes"
    - "events"
    - "componentstatuses"
    - "persistentvolumes"
    - "persistentvolumeclaims"
    - "namespaces"
    - "endpoints"
  verbs:
    - "get"
    - "list"
    - "watch"
- apiGroups:
    - "apps"
  resources:
    - "statefulsets"
    - "deployments"
    - "replicasets"
    - "daemonsets"
  verbs:
    - "get"
    - "list"
    - "watch"
- apiGroups:
    - "metrics"
    - "metrics.k8s.io"
  resources:
    - "*"
  verbs:
    - "*"
- apiGroups:
    - ""
  resources:
    - "nodes/metrics"
    - "nodes/proxy"
    - "nodes/stats"
  verbs:
    - "get"
- apiGroups:
    - "storage.k8s.io"
  resources:
    - "volumeattachments"
  verbs:
    - "get"
    - "list"
    - "watch"
- apiGroups:
    - "monitoring.coreos.com"
  resources:
    - "servicemonitors"
  verbs:
    - "get"
- apiGroups:
    - ""
  resources:
    - "api/componentstatuses"
  verbs:
    - "get"
    - "list"
- nonResourceURLs:
    - "/metrics"
  verbs:
    - "get"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Chart.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Chart.Name }}
subjects:
- kind: ServiceAccount
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
